version: "3.8"

services:
  mysql_order_db:
    env_file:
      - ./order_service/.env
    image: mysql:5.7
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - ./order_service/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  mysql_payment_db:
    env_file:
      - ./payment_service/.env
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: paymentpassword
      MYSQL_DATABASE: payment_db
      TZ: America/Sao_Paulo
    volumes:
      - ./payment_service/mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  order_service:
    build: ./order_service
    env_file:
      - ./order_service/.env
    depends_on:
      - mysql_order_db
    ports:
      - "8000:8000"

  payment_service:
    build: ./payment_service
    env_file:
      - ./payment_service/.env
    depends_on:
      - mysql_payment_db
    ports:
      - "5000:5000"
networks:
  default:
    driver: bridge
